config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'


  resources :apartments do
    resources :pictures
    resources :bookings
  end

  resources :bookings, only: [] do
    patch :validate, on: :member
    patch :cancel, on: :member
  end


  get '/profile', :to => "profile#show"

  get '/bookings', :to => "profile#bookings"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      # Define abilities for the passed in user here. For example:
      if user.admin?
        can :manage, :all
        can :access, :rails_admin # needed to access RailsAdmin
        can :dashboard            # dashboard access
      else
        can :read, :all
      end
  end
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base

  belongs_to :user
  has_many :pictures
  has_many :bookings

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :apartment
  belongs_to :user

  has_one :owner,
    class_name: 'User',
    through: :apartment,
    source: :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :apartment

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apartments

  has_many :bookings

  has_many :apartment_bookings,
    class_name: 'Booking',
    through: :apartments,
    source: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

  before_action :authenticate_user!, :only => :new

  def index
    @apartments = Apartment.all
  end

  def show
    @apartment = Apartment.find(params[:id])
    @owner = @apartment.user
  end

  def new
    @apartment = Apartment.new
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.user_id = current_user.id
    @apartment.save
    flash[:notif] = ">— Your apartment has been created with success —<"
    redirect_to apartments_path
  end

  def edit
    @apartment = Apartment.find(params[:id])
  end

  def update
     @apartment = Apartment.find(params[:id])
     @apartment.update(apartment_params)
     flash[:notif] = ">— Your apartment has been updated with success —<"
     redirect_to profile_path
  end

  def destroy
     @apartment = Apartment.find(params[:id])
     @apartment.destroy
     flash[:notice] = "The apartment '#{@apartment.title}’has been deleted !"
     redirect_to profile_path
  end


  private

  def apartment_params
    params.require(:apartment).permit(:title, :description, :price, :address, :zipcode, :city, :country, :picture)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

# def index
  # @apartment = Apartment.find(params[:apartment_id])
  # @bookings = Booking.find(params[:apartment_id])
# end

def create
  @apartment = Apartment.find(params[:apartment_id])
  @booking = @apartment.bookings.create(booking_params)
  @booking.status = "pending"
  @booking.user_id = current_user.id
  @booking.save
  @user = @booking.apartment.user
  UserMailer.new_booking_message(@user).deliver
  redirect_to apartment_path(@apartment)
end

def validate
  @booking = Booking.find(params[:id])
  @booking.status = "validated"
  @booking.save
  @user = @booking.user
  UserMailer.validation_message(@user).deliver
  redirect_to bookings_path
end


def cancel
  @booking = Booking.find(params[:id])
  @booking.status = "canceled"
  @booking.save
  @user = @booking.user
  UserMailer.cancel_message(@user).deliver
  redirect_to bookings_path
end

private

def booking_params
  params.require(:booking).permit(:checkin, :checkout, :guests)
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @apartments = Apartment.all
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @apartment = Apartment.find(params[:apartment_id])

    @pictures = @apartment.pictures.all
    @picture = Picture.new

  end

  def create
    @apartment = Apartment.find(params[:apartment_id])
    @apartment.pictures.create(picture_params)
    redirect_to apartment_pictures_path
  end

  def destroy
    @apartment = Apartment.find(params[:apartment_id])
    @picture = @apartment.pictures.find(params[:id])
    @picture.destroy
    redirect_to apartment_pictures_path
  end




  private

  def picture_params
    params.require(:picture).permit(:apartment_id, :picture)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
  end

  def bookings
  end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/apartments/edit.html.erb
<div class="well">
  <h1>Edit your apartment</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
        <%= form_for @apartment, html: { multipart: true} do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class:"form-control", placeholder:"ex : Beautiful 40sqm studio in the Bastille area"%>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control", placeholder:"ex : 2 bedrooms. Kitchen fully equiped."%>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_area :address, class:"form-control", placeholder:"ex : 34, rue du Petit Musc"%>
          </div>
          <div class="form-group">
            <%= f.label :city %>
            <%= f.text_area :city, class:"form-control", placeholder:"ex : Paris"%>
          </div>
          <div class="form-group">
            <%= f.label :zipcode %>
            <%= f.text_area :zipcode, class:"form-control", placeholder:"ex : 750005"%>
          </div>
          <div class="form-group">
            <%= f.label :country %>
            <%= f.text_area :country, class:"form-control", placeholder:"ex : France"%>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class:"form-control", placeholder:"ex : 110"%>
          </div>
          <%= f.submit "Submit", class: "btn btn-primary"%>
        <% end %>
        <br>
        <%= link_to 'Cancel', apartments_path %>
    </div>
  </div>
</div>

app/views/apartments/index.html.erb
  <div class="well">
    <h1>All the apartments :</h1>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>City</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @apartments.each do |apartment| %>
      <tr>
        <td><%= link_to apartment.title, apartment_path(apartment)%> </td>
        <td><%= apartment.city %></td>
        <td><%= apartment.price %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/apartments/new.html.erb
<div class="well">
  <h1>Create a new apartment</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
        <%= form_for @apartment, html: { multipart: true} do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class:"form-control", placeholder:"ex : Beautiful 40sqm studio in the Bastille area"%>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control", placeholder:"ex : 2 bedrooms. Kitchen fully equiped."%>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class:"form-control", placeholder:"ex : 34, rue du Petit Musc"%>
          </div>
          <div class="form-group">
            <%= f.label :city %>
            <%= f.text_field :city, class:"form-control", placeholder:"ex : Paris"%>
          </div>
          <div class="form-group">
            <%= f.label :zipcode %>
            <%= f.text_field :zipcode, class:"form-control", placeholder:"ex : 750005"%>
          </div>
          <div class="form-group">
            <%= f.label :country %>
            <%= f.text_field :country, class:"form-control", placeholder:"ex : France"%>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class:"form-control", placeholder:"ex : 110"%>
          </div>
          <%= link_to 'Cancel', apartments_path, class: "btn btn-default"%> <%= f.submit "Submit", class: "btn btn-primary"%>
        <% end %>
        <br>

    </div>
  </div>
</div>

app/views/apartments/show.html.erb
<div class="well">
  <h1><%= @apartment.title %> - <%= @apartment.price %>$ / night</h1>
  <%-# add a restriction so that only the owner can edit the data -%>
</div>

<div class="container">
  <div class="row">

   <div class="col-xs-4">
    <h3>Photos</h3>

      <div class="carousel-wrapper">
        <div class="carousel">
          <% @apartment.pictures.each do |picture| %>
            <div><%= image_tag picture.picture.url(:medium) %></div>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-xs-4">

      <h3>Details</h3>

      <p><strong>Description : </strong><%= @apartment.description %></p>
      <p><strong>Adress : </strong><%= @apartment.address %></p>
      <p><strong>Zipcode : </strong><%= @apartment.zipcode %></p>
      <p><strong>City : </strong><%= @apartment.city %></p>
      <p><strong>Country : </strong><%= @apartment.country %></p>

    </div>

    <div class="col-xs-4">

            <h3>Booking</h3>

        <p><strong>Owner : </strong><%= @owner.email %></p>
        <%= form_for([@apartment, @apartment.bookings.build]) do |b| %>

          <p><%= b.label :checkin %>
          <%= b.date_field :checkin %></p>

          <p><%= b.label :checkout %>
          <%= b.date_field :checkout %></p>

          <p><%= b.label :guests %>
          <%= b.number_field :guests %></p>

          <%= b.submit%>

        <% end %>
      </div>
  </div>
</div>




<!-- controllers et views pour afficher les demandes de bookings au proprio et au renter. -->

app/views/bookings/index.html.erb
<table class="table">

  <thead>
    <tr>
      <th>Apartment</th>
      <th>Checkin</th>
      <th>Checkout</th>
      <th>Guests</th>
    </tr>
  </thead>

  <tbody>

  <% @apartment.bookings.each do |booking| %>
    <tr>
      <td><%= booking.apartment_id %></td>
      <td><%= booking.checkin %></td>
      <td><%= booking.guests %></td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/home/index.html.erb
  <div class="search-area text-center">
    <div class="page-container page-container-responsive row-full-height">
      <div class="intro-area row row-table row-full-height" id="title">
        <div class="col-12 col-middle">
          <h1 id="tagline" class="uppercase text-jumbo text-contrast row-space-1">Welcome to our Badass Airbnb Community! </h1>
          <div id="subtitle" class="h4 text-contrast row-space-4">
            Our rentals make your next destination feel like home.</div>
            <a href="/apartments" class="btn btn-primary btn-lg active" role="button">Apartment Listings</a>
          <!-- ajouter une bouton avec les detailles -->
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_sessions.html.erb
<% if user_signed_in? %>
  <li class="sign-in-mail">Hi <%= current_user.email %> !</li>
  <li class="sign-in"><%= link_to 'Check your profile', profile_path %></li>
  <li class="sign-in"><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
<% else %>
  <li class="sign-in"><%= link_to 'Sign in', new_user_session_path %></li>
  <li class="sign-in"><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DopestAirbnb</title>
  <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/jquery.slick/1.3.7/slick.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class="wrapper">

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Badass Airbnb Apartments</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Apartments listing', apartments_path %></li>
            <li><%= link_to 'List an apartment', new_apartment_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'layouts/sessions' %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </div>

<script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.slick/1.3.7/slick.min.js"/></script>


</body>
</html>

app/views/pictures/index.html.erb
<h1>Photos list</h1>

<p>Nombre de photos : <%= @pictures.size %></p>


<% @apartment.pictures.each do |picture| %>
  <p><%= image_tag picture.picture.url(:medium) %> <%= link_to 'Delete', [picture.apartment, picture], method: :delete%></p>
<% end %>



<p>Ajouter une photo :</p>
<%= form_for [@apartment, @picture], html: { multipart: true } do |t| %>
  <p>
    <%= t.label :picture %>
    <%= t.file_field :picture %>
  </p>
<p>
  <%= t.submit %>
</p>

<% end %>